### ISSUE TITLE
Unit tests for line equation functions

### ISSUE THREAD

**Issue by jpkruger** [jpkruger/Classwork#16]
https://github.com/jpkruger/Classwork/blob/7904c1bd8c90eaa06138721b639062f3101289ce/test_line_equation.py#L1-L25

The additional exercises (determining if a point is on a line) were done before the initial exercise (calculating a y value from a set of points), so that's why the tests were written in that order.

**Comment by dward2** [comment]
Your unit tests look great.  Thanks.
